dist: trusty
sudo: false
language: python

branches:
  only:
    - master

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-test
    - python: 3.3
      env: TOXENV=py33-test
    - python: 3.4
      env: TOXENV=py34-test
    - python: 2.6
      env: TOXENV=py26-doctest
    - python: 2.7
      env: TOXENV=py27-doctest
    - python: 3.3
      env: TOXENV=py33-doctest
    - python: 3.4
      env: TOXENV=py34-doctest

install:
  - pip install -U tox pymongo

script:
  - tox
